export const FETCH_KMEANS = 'FETCH_KMEANS';
export const SPOTIFY_ACCESS_TOKEN = 'SPOTIFY_ACCESS_TOKEN';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_CLUSTER_LIST = 'FETCH_USER_CLUSTER_LIST';