export const FETCH_KMEANS = 'FETCH_KMEANS';
export const SPOTIFY_ACCESS_TOKEN = 'SPOTIFY_ACCESS_TOKEN';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_CLUSTER_LIST = 'FETCH_USER_CLUSTER_LIST';
export const DELETING_USER_CLUSTER = 'DELETING_USER_CLUSTER';
export const DELETED_USER_CLUSTER = 'DELETED_USER_CLUSTER';
export const SEARCH_FOR_USERS = 'SEARCHING_FOR_USERS';
export const LOADING_SEARCH_RESULTS = 'LOADING_SEARCH_RESULTS';